# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28c0ce93dca2673709854c01e635131814822f9fb8dbd965c0ed434f87181a68189ac826401a6f94fd7fe51bf2da29ec8d23df6bb23ed7bfa9c6aa0a924bfb0

test:
  secret_key_base: b8f922c9bd4517b0ae1bfdf93ed6f5a6caa1a1accb6bef9fc7b7b7b53bdd621227851cb84811e34e295a160b4169c50635804f71688cdc85eeff4fd6bd6ed7fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
